version: '3'

services:
  php:
    build:
      context: ./php
      args:
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini

networks:
  app-networks:
    driver: ${NETWORK_DRIVER}
